# -*- coding: utf-8 -*-
{
    'name': "Library ENSAH System",
    'version': '1.0',
    'summary': """Library ENSAH System""",
    'description': """discover our  Ensah   Library System """,
    'category': 'Science',
    'author': "RAKIB DOUHA && TOUHAMI WIAM",
    'company': 'ENSAH',
    'price': 5000.0,
    'currency': 'MAD',
    'website': "http://ensah.ma",
    'depends': ['base', 'board', 'mail','contacts'],

    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/report.xml',
        'views/Books_data.xml',
        'views/Author.xml',
        'views/Publisher.xml',
        'views/Borrows.xml',
        'views/Book_copies.xml',
        'views/Book_Category.xml',
        'views/res_partner.xml',
        'views/dashboard.xml',
        'views/menu.xml',
    ],
    'images': ['static/description/banner.gif'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
